-- Runtime business data, traces, and LangGraph checkpoints live in PostgreSQL.
-- The legacy SQLite files remain read-only migration sources/backups.

CREATE TABLE IF NOT EXISTS tenants (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL REFERENCES tenants(id),
    external_id TEXT NOT NULL,
    display_name TEXT,
    language TEXT DEFAULT 'zh',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, external_id)
);
CREATE TABLE IF NOT EXISTS conversations (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL REFERENCES tenants(id),
    user_id TEXT REFERENCES users(id),
    legacy_session_id TEXT UNIQUE,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_conversations_user ON conversations(tenant_id, user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS conversation_messages (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sequence_no INTEGER NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('user', 'assistant', 'system', 'tool')),
    content TEXT NOT NULL,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (conversation_id, sequence_no)
);
CREATE INDEX IF NOT EXISTS idx_conversation_messages_timeline ON conversation_messages(conversation_id, sequence_no);

CREATE TABLE IF NOT EXISTS conversation_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    user_message TEXT,
    bot_reply TEXT,
    intent TEXT,
    emotion TEXT,
    emotion_intensity INTEGER DEFAULT 1,
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_history_session ON conversation_history(session_id);
CREATE TABLE IF NOT EXISTS user_profiles (
    session_id TEXT PRIMARY KEY,
    name TEXT,
    preferred_name TEXT,
    language TEXT DEFAULT 'zh',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS user_preferences (
    session_id TEXT NOT NULL,
    product_interests JSONB,
    known_issues JSONB,
    communication_style TEXT,
    update_count INTEGER DEFAULT 1,
    PRIMARY KEY(session_id, product_interests)
);
CREATE TABLE IF NOT EXISTS tickets (
    ticket_id TEXT PRIMARY KEY,
    session_id TEXT,
    issue_category TEXT,
    description TEXT,
    resolution TEXT,
    satisfaction TEXT,
    priority TEXT,
    emotion TEXT,
    emotion_intensity INTEGER,
    message_count INTEGER,
    created_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    stars INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS conversation_feedback (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    message_id TEXT REFERENCES conversation_messages(id) ON DELETE SET NULL,
    kind TEXT NOT NULL CHECK(kind IN ('rating', 'reaction', 'satisfaction', 'review')),
    value_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_conversation_feedback_kind_time
    ON conversation_feedback(kind, created_at DESC);
CREATE TABLE IF NOT EXISTS tool_calls (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    message_id TEXT REFERENCES conversation_messages(id) ON DELETE SET NULL,
    tool_name TEXT NOT NULL,
    arguments_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    result_json JSONB,
    status TEXT NOT NULL CHECK(status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')),
    error_message TEXT,
    idempotency_key TEXT,
    duration_ms INTEGER,
    retry_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(conversation_id, idempotency_key)
);
CREATE TABLE IF NOT EXISTS legacy_history_migrations (
    legacy_history_id BIGINT PRIMARY KEY,
    conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS traces (
    request_id TEXT PRIMARY KEY,
    user_id TEXT,
    input_text TEXT,
    total_latency_ms DOUBLE PRECISION,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    trace_json JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_traces_user ON traces(user_id);
CREATE INDEX IF NOT EXISTS idx_traces_time ON traces(completed_at DESC);

-- Negative feedback is triaged here before any human-approved product or prompt change.
CREATE TABLE IF NOT EXISTS feedback_improvement_queue (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL REFERENCES tenants(id),
    conversation_id TEXT REFERENCES conversations(id) ON DELETE SET NULL,
    trace_id TEXT REFERENCES traces(request_id) ON DELETE SET NULL,
    feedback_id TEXT REFERENCES conversation_feedback(id) ON DELETE SET NULL,
    issue_type TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'normal' CHECK(severity IN ('low', 'normal', 'high')),
    status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open', 'triaged', 'resolved', 'dismissed')),
    user_comment TEXT,
    evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    owner TEXT,
    resolution_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_feedback_queue_active
    ON feedback_improvement_queue(tenant_id, status, severity, created_at DESC);
