-- Complete PostgreSQL + pgvector runtime schema.
-- Idempotent: safe on a fresh database and on databases initialized by 001/002.

CREATE EXTENSION IF NOT EXISTS vector;

INSERT INTO tenants (id, name, created_at)
VALUES ('default', 'Default tenant', NOW())
ON CONFLICT (id) DO NOTHING;

ALTER TABLE users ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TEXT;
UPDATE users SET user_id = COALESCE(user_id, external_id, id) WHERE user_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_user_id ON users(user_id);

CREATE TABLE IF NOT EXISTS sessions (
    session_id TEXT PRIMARY KEY,
    user_id TEXT,
    title TEXT,
    created_at TEXT,
    last_active TEXT,
    message_count INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id, last_active DESC);

ALTER TABLE conversation_history ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE user_preferences ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS idx_history_user ON conversation_history(user_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_profiles_user ON user_profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_prefs_user ON user_preferences(user_id);
CREATE INDEX IF NOT EXISTS idx_tickets_user ON tickets(user_id);

ALTER TABLE ratings ADD COLUMN IF NOT EXISTS message_index INTEGER;
ALTER TABLE ratings ADD COLUMN IF NOT EXISTS rated_at TEXT;
CREATE TABLE IF NOT EXISTS reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    message_id TEXT,
    emoji TEXT,
    active INTEGER,
    reacted_at TEXT
);
CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    query TEXT,
    answer TEXT,
    rating INTEGER,
    comment TEXT,
    created_at TEXT
);

CREATE TABLE IF NOT EXISTS user_memories (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    tenant_id TEXT NOT NULL DEFAULT 'default',
    content TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'fact',
    embedding vector(1024),
    importance REAL NOT NULL DEFAULT 0.5,
    created_at TEXT NOT NULL,
    expires_at TEXT,
    source_session TEXT,
    dedup_key TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_um_user ON user_memories(user_id, tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_um_dedup ON user_memories(dedup_key);
CREATE INDEX IF NOT EXISTS idx_um_embedding_hnsw
    ON user_memories USING hnsw (embedding vector_cosine_ops)
    WHERE embedding IS NOT NULL AND is_deleted = FALSE;

-- Shared counters used by the observability dashboard. Unlike process-local
-- Prometheus gauges, these survive backend restarts and multiple workers.
CREATE TABLE IF NOT EXISTS rag_metric_state (
    metric_name TEXT PRIMARY KEY,
    queries BIGINT NOT NULL DEFAULT 0,
    hits BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (queries >= 0 AND hits >= 0 AND hits <= queries)
);

ALTER TABLE traces ADD COLUMN IF NOT EXISTS session_id TEXT;
ALTER TABLE traces ADD COLUMN IF NOT EXISTS tenant TEXT;
ALTER TABLE traces ADD COLUMN IF NOT EXISTS scene TEXT;
ALTER TABLE traces ADD COLUMN IF NOT EXISTS total_ms DOUBLE PRECISION;
ALTER TABLE traces ADD COLUMN IF NOT EXISTS cost DOUBLE PRECISION;
ALTER TABLE traces ADD COLUMN IF NOT EXISTS failed INTEGER;
ALTER TABLE traces ADD COLUMN IF NOT EXISTS low_score INTEGER;
ALTER TABLE traces ADD COLUMN IF NOT EXISTS created_at TEXT;
CREATE INDEX IF NOT EXISTS idx_traces_session ON traces(session_id);
CREATE INDEX IF NOT EXISTS idx_traces_created ON traces(created_at DESC);

CREATE TABLE IF NOT EXISTS bad_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts DOUBLE PRECISION NOT NULL,
    session_id TEXT NOT NULL DEFAULT '',
    request_id TEXT NOT NULL DEFAULT '',
    query TEXT NOT NULL DEFAULT '',
    answer TEXT NOT NULL DEFAULT '',
    signal_type TEXT NOT NULL CHECK (signal_type IN
      ('rating','reaction','feedback','escalation','repeat_question')),
    score DOUBLE PRECISION,
    comment TEXT NOT NULL DEFAULT '',
    trace_ref TEXT NOT NULL DEFAULT '',
    processed INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_bad_cases_processed ON bad_cases(processed, ts);
CREATE INDEX IF NOT EXISTS idx_bad_cases_session ON bad_cases(session_id, ts);
CREATE TABLE IF NOT EXISTS session_last_query (
    session_id TEXT PRIMARY KEY,
    query TEXT NOT NULL,
    ts DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS prompt_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    kind TEXT NOT NULL DEFAULT 'system',
    created_at DOUBLE PRECISION NOT NULL
);
CREATE TABLE IF NOT EXISTS prompt_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES prompt_template(id),
    version_no INTEGER NOT NULL,
    content TEXT NOT NULL,
    variables_schema TEXT NOT NULL DEFAULT '[]',
    parent_version_id BIGINT,
    status TEXT NOT NULL DEFAULT 'candidate',
    change_reason TEXT NOT NULL DEFAULT '',
    diff TEXT,
    created_at DOUBLE PRECISION NOT NULL,
    UNIQUE(template_id, version_no)
);
CREATE TABLE IF NOT EXISTS prompt_release (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES prompt_template(id),
    version_id BIGINT NOT NULL REFERENCES prompt_version(id),
    env TEXT NOT NULL DEFAULT 'prod',
    tenant TEXT,
    percent INTEGER NOT NULL DEFAULT 100,
    active INTEGER NOT NULL DEFAULT 1,
    created_at DOUBLE PRECISION NOT NULL
);
CREATE TABLE IF NOT EXISTS prompt_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL,
    version_id BIGINT NOT NULL,
    session_id TEXT NOT NULL DEFAULT '',
    ts DOUBLE PRECISION NOT NULL
);
CREATE TABLE IF NOT EXISTS eval_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts DOUBLE PRECISION NOT NULL,
    prompt_name TEXT NOT NULL,
    candidate_version INTEGER,
    baseline_version INTEGER,
    candidate_pass_rate DOUBLE PRECISION,
    baseline_pass_rate DOUBLE PRECISION,
    judge_wins INTEGER,
    judge_losses INTEGER,
    judge_ties INTEGER,
    passed INTEGER NOT NULL DEFAULT 0,
    details TEXT NOT NULL DEFAULT '{}'
);
